name: macos-latest

on:
  push:
    branches:
      - "develop"

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - name: Install packages
        run: |
          brew install doxygen
      - name: Check out opt-65816
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: opt-65816
          fetch-depth: 0
          submodules: true
      - name: Compilation of opt-65816 & tests
        run: |
          sudo ln -s /usr/local/bin/gcc-12 /usr/local/bin/gcc
          sudo ln -s /usr/local/bin/g++-12 /usr/local/bin/g++
          cd opt-65816
          make clean
          CFLAGS+=-I/usr/local/include make
          make tests
      - name: Generate doxygen documentation
        run: |
          cd opt-65816
          make clean
          make doc
