name: macos-latest

on:
  push:
    branches:
      - "develop"

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
      - name: Install packages
        run: |
          brew install pcre
          brew install doxygen
      - name: Check out opt-65816
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: opt-65816
          fetch-depth: 0
          submodules: true
      - name: Compilation of opt-65816 & tests
        run: |
          cd opt-65816
          make clean
          CC="gcc-12" CFLAGS+=-I/usr/local/Cellar/pcre/8.45/include make
          CC="gcc-12" CFLAGS+=-I/usr/local/Cellar/pcre/8.45/include make tests
      - name: Generate doxygen documentation
        run: |
          cd opt-65816
          make clean
          make doc
