name: ubuntu-latest

on:
  push:
    branches:
      - "develop"

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y build-essential gcc-multilib git cmake wget valgrind doxygen
      - name: Check out opt-65816
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: opt-65816
          fetch-depth: 0
          submodules: true
      - name: Compilation of opt-65816 & tests
        run: |
          cd opt-65816
          make clean
          make
          make tests
      - name: Check memory leaks
        run: |
          cd opt-65816
          make clean
          make valgrind
      - name: Generate doxygen documentation
        run: |
          cd opt-65816
          make clean
          make doc
