name: windows-latest

on:
  push:
    branches:
      - "develop"

jobs:
  windows-latest:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          release: true
          msystem: UCRT64
          install: >-
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-pcre
            msys2-runtime
            git
            doxygen
            zip
            python
            doxygen
      - name: Check out opt-65816
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: opt-65816
          fetch-depth: 0
          submodules: true
      - name: Compilation of opt-65816 & tests
        run: |
          echo "PATH            = $PATH"
          echo "gcc location    = $(which gcc)"
          echo "gcc++ location  = $(which gcc)"
          echo "gcc version     = $(gcc --version)"
          echo "gcc++ version   = $(g++ --version)"
          cd opt-65816
          make clean
          make
          ldd 816-opt*
      # - name: Generate doxygen documentation
      #   run: |
      #     cd opt-65816
      #     make clean
      #     make doc
