name: windows_msys2

on:
  push:
    branches:
      - "main"
      - "develop"
      - "pcre"
      - "test"

jobs:
  amd64_windows_gcc:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            git
            pcre
      - run: gcc -v
