name: windows_msys2

on:
  push:
    branches:
      - "main"
      - "develop"
      - "pcre"
      - "tests"

jobs:
  amd64_windows_gcc:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            gcc
            make
            cmake
            pcre
            git
      - run: gcc -v
      - run: cmake --version
      - run: git -v
      - run: make clean
      - run: make -n
