name: windows-latest

on:
  push:
    branches:
      - "develop"

jobs:
  windows-latest:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install dependencies
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            gcc
            make
            cmake
            pcre-devel
            git
            python
            doxygen
      - name: Check out opt-65816
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: opt-65816
          fetch-depth: 0
          submodules: true
      - name: Compilation of opt-65816 & tests
        run: |
          cd opt-65816
          make clean
          make
          make tests
      - name: Generate doxygen documentation
        run: |
          cd opt-65816
          make clean
          make doc
