name: windows_msys2

on:
  push:
    branches:
      - "main"
      - "develop"
      - "pcre"
      - "tests"

jobs:
  amd64_windows_gcc:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Windows Depends MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            gcc
            make
            cmake
            pcre
            git
      - run: |
          gcc -v
          cmake --version
          git -v
      - name: Check out PVSNESLIB
        uses: actions/checkout@v3
        with:
          ref: pcre
          path: opt-65816
          fetch-depth: 0
      - run: |
          pwd
          ls -rtl
