name: msys2_windows-2019

on:
  push:
    branches:
      - "main"
      - "develop"

jobs:
  windows-2019:
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Windows Depends MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            gcc
            make
            cmake
            pcre-devel
            git
            python
            doxygen
      - name: Print development tools versions
        run: |
          echo "* gcc version:"
          gcc -v
          echo
          echo "* cmake version:"
          cmake --version
          echo
          echo "* git version:"
          git -v
          echo
          echo "* python version:"
          python --version
          echo
          echo "* msys2 version:"
          uname -a
          echo
          echo "* msys2 package versions:"
          pacman -Qe
          echo
      - name: Check out opt-65816
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          path: opt-65816
          fetch-depth: 0
          submodules: true
      - name: Compilation of opt-65816 & tests
        run: |
          cd opt-65816
          make clean
          make -n
          make
          make tests
          make doc
